name: "Main workflow"
on: [pull_request, push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: "Install build deps on linux"
        run:   |
          echo $RUNNER_OS;
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get install libusb-1.0-0-dev
               sudo apt-get install libudev-dev
          fi
        shell: bash
      - name: "Install dependencies"
        run: yarn install --network-timeout 1000000
      - name: "Build application"
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_ID_TEAM: ${{ secrets.APPLE_ID_TEAM }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        run:   | 
          if [ "$RUNNER_OS" == "macOS" ]; then
              PYTHON_PATH=$(which python3)
          fi
          yarn dist
        shell: bash
